In [1]:
# 1.bag of words
#  we use countvectorization

In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.DataFrame({'text':['people watch cricket','player was player',
                         'people write comment',
                         'cricket play comment' ] ,'output':[1,1,0,0]})

In [4]:
df

text  output
0  people watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [5]:
# player watch cricket player was write comment play
# [11100000]
# [00021000]
# [10000110]
# [00100011]

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [7]:
bow=cv.fit_transform(df['text'])

In [8]:
# vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 6, 'cricket': 1, 'player': 4, 'was': 5, 'write': 7, 'comment': 0, 'play': 3}


In [9]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 0 0 0 1 0]]
[[0 0 0 0 2 1 0 0]]


In [10]:
cv.transform(["cricket watch and write comment of cricket comment"]).toarray()

array([[2, 2, 0, 0, 0, 0, 1, 1]])

In [11]:
# 2.N-grams

In [12]:
# cv=CountVectorizer(ngram_range(2,2))

In [13]:
v=CountVectorizer(ngram_range=(1,2))
# cv=CountVectorizer(ngram_range(2,2))

In [14]:
bow=v.fit_transform(df['text'])

In [15]:
df['text']

0    people watch cricket
1       player was player
2    people write comment
3    cricket play comment
Name: text, dtype: object

In [16]:
# vocab
v.vocabulary_

{'people': 3,
 'watch': 12,
 'cricket': 1,
 'people watch': 4,
 'watch cricket': 13,
 'player': 8,
 'was': 10,
 'player was': 9,
 'was player': 11,
 'write': 14,
 'comment': 0,
 'people write': 5,
 'write comment': 15,
 'play': 6,
 'cricket play': 2,
 'play comment': 7}

In [17]:
# TF(term frequency)
# 2.IDF(inverse document frequency)

In [18]:
# TF(t,d)=(number of ocurences of terms t in document d)/
# (total number of terms in the document d)
# example==>
# d1 = people watch cricket

# tf(people,d1) =1/3

# d2=match was match.
# tf(match,d2) = 2/3